### ISSUE TITLE
all docs served via gitbook.io are broken

### ISSUE THREAD

**Issue by fermulator** [MycroftAI/documentation#165]
if i hit up https://mycroft.ai/documentation
it is in raw markdown 

and any link seems to redirect there

consider

https://duckduckgo.com/?q=mycroft+linux+pocketsphinx&t=lm&atb=v179-1&ia=web

links to
https://mycroft-ai.gitbook.io/docs/using-mycroft-ai/get-mycroft/linux
, which redirects to the root doc
https://mycroft.ai/documentation

**Comment by krisgesling** [comment]
Thanks for the heads up fermulator. All the links should be working now.

The main /documentation might take a few minutes for caches to refresh

**Comment by fermulator** [comment]
Verified fixed! Thank you.

**Comment by fermulator** [comment]
(what was the root cause out of curiosity?)

**Comment by krisgesling** [comment]
My fault :sweat_smile: 

I was looking at DNS settings in the Gitbook GUI so we can switch it over to docs.mycroft.ai rather than https://mycroft-ai.gitbook.io/docs/

For some reason hitting cancel saved the changes instead of leaving them as is which meant Gitbook was trying to connect to that subdomain and ending up at our old docs.

PSA: Don't even look at the DNS settings of a production system!
