### ISSUE TITLE
Documentation mentions the partition iso whole disk when using dd to write the image

### ISSUE THREAD

**Issue by schoolsplay** [MycroftAI/documentation#214]
**Describe the bug**
Documentation mentions wrong device when using dd to write the image.
https://mycroft-ai.gitbook.io/docs/using-mycroft-ai/get-mycroft/picroft#burn-the-disk-image-to-the-micro-sd-card states the following:

```
Run the command sudo dd if=path-to-your-image.img of=/dev/sdb1 bs=20M. Make sure to substitute the location of your device,
 and the path to the .img file you downloaded.
```

In this example it should be 'sdb', using the whole disk not the partition, when writing the image with dd.
Writing the image to a partition will not produce a bootable disk

**Comment by krisgesling** [comment]
Hey thanks for picking this up - definitely not correct!

I've done a quick update, including a wildcard on the umount command to ensure all partitions are unmounted before continuing. So it should be fixed by: https://github.com/MycroftAI/documentation/commit/f8c5566b53a583dca2f8eb25c61d9487abbad072

If you want to join [our public contributors list](github.com/mycroftAI/contributors) please complete a CLA request at https://mycroft.ai/cla

Thanks again :)
